include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_constructors_over_static_methods: false

analyzer:
  exclude:
    - [plugins/**]
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  enable-experiment:
    - non-nullable

  strong-mode:
    implicit-casts: false

  errors:
    missing_return: error
    missing_required_param: error
    parameter_assignments: error